version: '3.8'

services:
  backend-app:
    image: suprabhat-retail-app:1.0
    container_name: retail-app
    ports:
      - "9090:8080"  # host:container
    restart: unless-stopped

  frontend-app:
    image: suprabhat-retail-app-frontend:1.0
    container_name: retail-app-frontend
    ports:
      - "8081:8080"  # map host 8081 to container 8080
    restart: unless-stopped
