---
# This defines the Deployment, which manages the running instances (Pods) of your app.
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-maven-app-deployment
spec:
  replicas: 2 # Tell Kubernetes to run 2 copies (Pods) of your application.
  selector:
    matchLabels:
      app: my-maven-app
  template:
    metadata:
      labels:
        app: my-maven-app
    spec:
      containers:
        - name: my-maven-app-container
          # This is the image that will be pulled from Docker Hub.
          # ==> IMPORTANT: Replace 'yourdockerhubusername' with your actual Docker Hub username.
          image: manraj110/my-maven-app:latest
          ports:
            - containerPort: 8090
---
# This defines the Service, which exposes your application to be accessed.
apiVersion: v1
kind: Service
metadata:
  name: my-maven-app-service
spec:
  # 'LoadBalancer' makes the service accessible from your Mac's localhost.
  type: LoadBalancer
  selector:
    app: my-maven-app
  ports:
    - protocol: TCP
      port: 8090 # The port you will access the service on.
      targetPort: 8090 # The port inside the container to send traffic to.
