apiVersion: apps/v1
kind: Deployment
metadata:
  name: social-media-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: social-media
  template:
    metadata:
      labels:
        app: social-media
    spec:
      containers:
      - name: social-app
        image: social-media-app:latest
        imagePullPolicy: Never  # Changed from Always to Never (use local image)
        ports:
        - containerPort: 8081
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 512Mi