apiVersion: v1
kind: ConfigMap
metadata:
  name: user-config
  namespace: exp8
data:
  LOG_LEVEL: info
  USER_SERVICE_PORT: "8081"

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: auth-config
  namespace: exp8
data:
  LOG_LEVEL: info
  AUTH_SERVICE_PORT: "8082"

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: product-config
  namespace: exp8
data:
  LOG_LEVEL: info
  PRODUCT_SERVICE_PORT: "8083"

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: order-config
  namespace: exp8
data:
  LOG_LEVEL: info
  ORDER_SERVICE_PORT: "8084"
