apiVersion: v1
kind: ConfigMap
metadata:
  name: httpd-content
  namespace: exp9
data:
  index.html: |
    <!doctype html>
    <html>
      <head>
        <meta charset="utf-8" />
        <title>Exp9 Apache</title>
      </head>
      <body>
        <h1>Apache on Kubernetes - Exp9 by Manan Bhimjiyani</h1>
        <p>Deployed in namespace <strong>exp9</strong></p>
      </body>
    </html>
